import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const exec=promisify(execFile);const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,"..");const managerPublic=path.join(here,"public");const dataFile=path.join(root,"data","knowledge.json");const uploadDir=path.join(root,"uploads");const port=4178;
const types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".pdf":"application/pdf"};
function send(res,status,body,type="application/json; charset=utf-8"){res.writeHead(status,{"content-type":type,"cache-control":"no-store"});res.end(typeof body==="string"?body:JSON.stringify(body))}
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>36*1024*1024)throw new Error("文件太大，单个附件请控制在25MB以内");chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString("utf8")||"{}")}
function safeName(name){return path.basename(name).replace(/[^\p{L}\p{N}._-]+/gu,"-").slice(0,120)||`file-${Date.now()}`}
async function staticFile(res,base,relative){const target=path.resolve(base,relative||"index.html");if(!target.startsWith(path.resolve(base)))return send(res,403,"禁止访问","text/plain");try{const stat=await fs.stat(target);const file=stat.isDirectory()?path.join(target,"index.html"):target;send(res,200,await fs.readFile(file),types[path.extname(file).toLowerCase()]||"application/octet-stream")}catch{send(res,404,"未找到页面","text/plain; charset=utf-8")}}
async function git(args){return exec("git",args,{cwd:root,windowsHide:true,maxBuffer:1024*1024})}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://127.0.0.1");if(url.pathname==="/api/data"&&req.method==="GET")return send(res,200,await fs.readFile(dataFile,"utf8"),"application/json; charset=utf-8");if(url.pathname==="/api/data"&&req.method==="POST"){const value=await body(req);if(!Array.isArray(value.sections)||!Array.isArray(value.articles))throw new Error("知识库数据格式不正确");const temp=`${dataFile}.tmp`;await fs.writeFile(temp,JSON.stringify(value,null,2),"utf8");await fs.rename(temp,dataFile);return send(res,200,{ok:true})}if(url.pathname==="/api/upload"&&req.method==="POST"){const value=await body(req);const name=safeName(value.name);const match=String(value.data||"").match(/^data:[^;]+;base64,(.+)$/);if(!match)throw new Error("附件内容无效");await fs.mkdir(uploadDir,{recursive:true});const final=`${Date.now()}-${name}`;await fs.writeFile(path.join(uploadDir,final),Buffer.from(match[1],"base64"));return send(res,200,{ok:true,path:`uploads/${final}`})}if(url.pathname==="/api/status"){const result=await git(["status","--short"]);return send(res,200,{changed:Boolean(result.stdout.trim()),details:result.stdout.trim()})}if(url.pathname==="/api/publish"&&req.method==="POST"){await git(["config","user.name","YanZhao365"]);await git(["config","user.email","YanZhao365@users.noreply.github.com"]);await git(["add","."]);try{await git(["commit","-m",`更新知识库 ${new Date().toLocaleString("zh-CN")}`])}catch(error){if(!String(error.stderr||"").includes("nothing to commit"))throw error}await git(["push","-u","origin","HEAD:main"]);return send(res,200,{ok:true,message:"发布成功，线上网站即将更新"})}if(url.pathname==="/manager"||url.pathname==="/manager/")return staticFile(res,managerPublic,"index.html");if(url.pathname.startsWith("/manager/"))return staticFile(res,managerPublic,url.pathname.slice(9));if(url.pathname.includes(".git")||url.pathname.startsWith("/manager/server"))return send(res,403,"禁止访问","text/plain");return staticFile(res,root,url.pathname.slice(1)||"index.html")}catch(error){send(res,500,{ok:false,error:error.message,details:String(error.stderr||"").trim()})}});
server.listen(port,"127.0.0.1",()=>console.log(`沿昭知识库管理器已启动：http://127.0.0.1:${port}/manager/`));

